using UnityEngine;
using System.Collections;

namespace ConstCollections.PJEnums
{
  public enum SCENE_LIST
  {
    TITLE,
    CREATE_HERO,
    BATTLE
  }

  public enum STRINGS_LABEL
  {
    BLANK = -1,
    CREDITS = 0,
    SETTINGS_TITLE,
    AUDIO_BLOCK,
    LANG_BLOCK,
    OTHERS_BLOCK,
    CREDITS_BUTTON,
    BGM_LABEL,
    SE_LABEL,
    TITLE_HOW_TO_PLAY_BUTTON,
    TITLE_LANGUAGE_SETTING_BUTTON,
    TITLE_DELETE_LOCAL_DATA_BUTTON,
    TITLE_UPLOAD_LOCAL_DATA_BUTTON,
    TITLE_DOWNLOAD_DATA_BUTTON,
    GO_BACK,
    TITLE_SETTINGS_BUTTON,
    TITLE_CREATE_HERO_BUTTON,
    TITLE_CONTINUE_GAME_BUTTON,
    CONFIRMATION_BUTTON,
    TITLE_CONFIRMATION_MESSAGE,
    CREATE_CHARACTER_REFRESH_BUTTON,
    CREATE_CHARACTER_NAME_LABEL,
    CREATE_CHARACTER_ATTRIBUTE_TITLE,
    STRENGTH,
    PHYSIQUE,
    SAGACITY,
    DEXTERITY,
    CREATE_CHARACTER_TITLE,
    HERO_INFORMATION_TITLE,
    HERO_INFORMATION_NEXT_LEVEL,
    HERO_INFORMATION_SKILL_POINT,
    HERO_INFORMATION_LIFE,
    HERO_INFORMATION_RESISTANCE,
    HERO_INFORMATION_ATK,
    HERO_INFORMATION_MAG,
    HERO_INFORMATION_DEF,
    HERO_INFORMATION_AC,
    HERO_INFORMATION_CRI,
    HERO_INFORMATION_PEN,
    HERO_INFORMATION_HIT,
    HERO_INFORMATION_AVOID,
    HERO_INFORMATION_NEXT_JUMP_BUTTON,
    NEXT_JUMP_HERO_LESS_THAN_THREE_DESCRIPTION,
    NEXT_JUMP_HERO_LESS_THAN_THREE_CONFIRMATION,
    NEXT_JUMP_HERO_FULL_TITLE,
    NEXT_JUMP_HERO_FULL_DESCRIPTION,
    NEXT_JUMP_HERO_SAVE_BUTTON,
    HERO_INFORMATION_SKILL_BUTTON,
    HERO_INFORMATION_EQUIPMENT_BUTTON,
    SKILL_INFORMATION_LEVEL_MARKING,
    SKILL_INFORMATION_LEVEL_MAX,
    HERO_INFORMATION_EXP,
    SKILL_INFORMATION_RESET_SKILL_BUTTON,
    SKILL_INFORMATION_TITLE,
    SKILL_INFORMATION_LEARN_BUTTON,
    SKILL_INFORMATION_UPGRADE_BUTTON,
    SKILL_INFORMATION_ADVANCE_BUTTON,
    SKILL_INFORMATION_TRAINING_BUTTON,
    SKILL_INFORMATION_ADVANCE_TITLE,
    SKILL_INFORMATION_ADVANCE_SELECT_BUTTON,
    SKILL_INFORMATION_MASTER_TITLE,
    BATTLE_MAIN_BOTTOM_MAP_BUTTON,
    BATTLE_MAIN_BOTTOM_HERO_BUTTON,
    BATTLE_MAIN_BOTTOM_ACHIEVEMENT_BUTTON,
    BATTLE_MAIN_BOTTOM_STONE_BUTTON,
    BATTLE_MAIN_BOTTOM_BATTLE_BUTTON,
    BATTLE_MAIN_BOTTOM_SETTINGS_BUTTON,
    BATTLE_TOP_AURA,
    BATTLE_TOP_DIMENSION_CHIP,
    BATTLE_AREA_SEARCH_PROGRESS,
    BATTLE_AREA_BOSS_BUTTON_LABEL,
    SKILL_UNACQUIRED,
    EQUIPMENT_INFORMATION_TITLE,
    EQUIPMENT_INFORMATION_EXCHANGE_BUTTON,
    EQUIPMENT_INFORMATION_REINFORCEMENT,
    EQUIPMENT_INFORMATION_BUILD,
    EQUIPMENT_EXCHANGE_TITLE,
    EQUIPMENT_TAKE_ON_LABEL,
    EQUIPMENT_BUILD_NEW_BUTTON,
    EQUIPMENT_NEW_EQUIPMENT_TITLE,
    EQUIPMENT_DESTROY_BUTTON,
    EQUIPMENT_ATTRIBUTE_COMPARISON,
    EQUIPMENT_EXCHANGE_EQUIPMENTS_BUTTON,
    EQUIPMENT_REINFORCEMENT_TITLE,
    EQUIPMENT_REINFORCEMENT_BUTTON,
    EQUIPMENT_REINFORCEMENT_LEVEL1_BUTTON,
    EQUIPMENT_REINFORCEMENT_LEVEL2_BUTTON,
    EQUIPMENT_REINFORCEMENT_LEVEL3_BUTTON,
    EQUIPMENT_REINFORCEMENT_MIRACLE_BUTTON,
    EQUIPMENT_REINFORCEMENT_SUCCESS_RATE_LABEL,
    EQUIPMENT_BUILD_LEVEL_LESS_THAN_TEN_THOUSAND_BUTTON,
    EQUIPMENT_BUILD_LEVEL_MORE_THAN_TEN_THOUSAND_BUTTON,
    EQUIPMENT_COMPARISON,
    EQUIPMENT_DESTROY_ACQUIRE_DIMENSION_CHIP_TITLE,
    EQUIPMENT_DESTROY_ACQUIRE_DIMENSION_CHIP_DESCRIPTION,
    EQUIPMENT_NONE_TEXT,
    EQUIPMENT_DESTROY_ACQUIRE_DIMENSION_CHIP_NUMBER,
    EQUIPMENT_DESTROY_CONFIRM_TITLE,
    EQUIPMENT_DESTROY_DESCRIPTION,
    EQUIPMENT_DESTROY_CONFIRM,
    EQUIPMENT_TYPE_WEAPON,
    EQUIPMENT_TYPE_ARMOR,
    EQUIPMENT_TYPE_DECORATIONS,
    TITLE_CONFIRMATION_TITLE_TEXT,
    BATTLE_AREA_SEARCH_PROGRESS_100,
    THOUSANDS_PLACE_COMMA,
    TITLE_START_GAME_BUTTON,
    SETTING_GAME_DESCRIPTIOM,
    SETTING_GAME_STAFF,
    HERO_INFORMATION_NEXT_JUMP_LEVEL_NOT_ENOUGH,
    HERO_INFORMATION_NEXT_JUMP_BOSS_FIGHTING,
    HERO_INFORMATION_SKILL_LAYOUT,
    HERO_INFORMATION_EQUIPMENT_LAYOUT
  } 
    
  public enum COMPARE_TYPE
  {
    NONE,
    EQUAL,
    SMALLER,
    GREATER
  }
}

namespace ConstCollections.PJEnums.Battle
{
  public enum BATTLE_TYPE
  {
    MONSTER_BATTLE,
    BOSS_BATTLE,
    EX_BOSS_BATTLE
  }

  public enum BATTLE_FIGHT_TYPE
  {
    NONE,
    ATTACKER,
    DEFENDER
  }

  public enum TURN_STATES
  {
    NONE,
    INIT,
    JUDGE_ACTIVE_DOT,
    JUDGE_DEAD_DOT,
    JUDGE_SPECIAL_SKILL,
    JUDGE_FROZEN,
    JUDGE_DIZZY,
    JUDGE_INITIATIVE_SKILL,
    JUDGE_ASSIST_ATTACK,
    DECIDE_ATTACK_TARGET,
    JUDGE_HIT_COUNT,
    JUDGE_HIT,
    JUDGE_INITIATIVE_SKILL_TYPE,
    RESURRECTION,
    CHANGE_HP,
    JUDGE_BLAST,
    CALCULATE_BLAST_POWER,
    CALCULATE_ATTACK_POWER,
    OUTPUT_DAMAGE,
    BACK_DAMAGE,
    JUDGE_DEAD,
    JUDGE_DEBUFF,
    JUDGE_STATE_EXCEPTION,
    JUDGE_ASSIGN_DOT,
    CHECK_TURN_COUNT,
    CHECK_PERSISTENCE_EFFECT
  }

  public enum ATTACK_POWER_TYPE
  {
    NONE,
    NORMAL,
    INITIATIVE_SKILL,
    DISABLED
  }

  public enum CHANGE_BATTLE_TURN
  {
    NONE,
    BREAK_TO_TURN_END,
  }

  public enum INFO_FORMAT_LABEL
  {
    NONE,
    BLANK_LINE,
    HERO_NAME,
    ENEMY_NAME,
    SKILL_NAME,
    NORMAL_ATTACK_NAME,
    ACTIVE_ATTACK,
    ACTIVE_SKILL,
    AVOID_ATTACK,
    GET_DAMAGE,
    NORMAL_DAMAGE,
    BLAST_DAMAGE,
    MARK_NAGATIVE,
    MARK_POSITIVE,
    MARK_SPLIT,
    BATTLE_ENGAGE,
    BATTLE_DONE,
    GOT_EXP,
    LEVEL_UP,
    GOT_AURA,
    GOT_DIMENSION_CHIP,
    IS_DEAD,
    SKILL_DOT_BURN_ATTACH,
    SKILL_DOT_BURN_DAMAGE,
    SKILL_DOT_POISON_BE_BURN,
    SKILL_DOT_POISON_ATTACH,
    SKILL_DOT_POISON_DAMAGE,
    SKILL_MUST_FAILED,
    DEFENDER_AC_DOWN,
    DEFENDER_ATK_DOWN_DEF_DOWN,
    DEFENDER_HIT_DOWN_AVD_DOWN,
    DEFENDER_HIT_DOWN_AVD_DOWN_CRI_DOWN,
    HP_UP,
    HP_DOWN,
    RESURRECTION,
    SKILL_EXCEPTION_FROZEN_ATTACH,
    SKILL_EXCEPTION_DIZZY_ATTACH,
    SKILL_EXCEPTION_FROZEN_ACTIVED,
    SKILL_EXCEPTION_DIZZY_ACTIVED,
    SKILL_EXCEPTION_FROZEN_REMOVED,
    SKILL_EXCEPTION_DIZZY_REMOVED,
    VARIABLE_TEXT
  }
}

namespace ConstCollections.PJEnums.HangUp
{
  public enum STRINGS_LABEL
  {
    BLANK,
    TITLE_NORMAL,
    OFFLINE_TIME_TEXT,
    GET_EXP_TEXT,
    GET_AURA_TEXT,
    GET_DIMENSION_CHIP_TEXT,
    BUTTON_GET,
    BUTTON_AD_VIDEO,
    TITLE_CONNECTION_ERROR,
    CONNECTION_ERROR_TEXT,
    BUTTON_OK,
    TITLE_WAITING,
    WAITING_TEXT,
    BUTTON_AGAIN,
    BUTTON_PASS,
    TITLE_DOUBLE_REWARD
  }
}

namespace ConstCollections.PJEnums.Character
{
  public enum ANIMATION_STATES
  {
    NONE,
    IDLE,
    ATTACK,
    GET_DAMAGE,
    DEAD
  }

  public enum ANIMATION_TRIGGERS
  {
    GOTO_IDLE,
    GOTO_ATTACK,
    GOTO_GET_DAMAGE,
    GOTO_DEAD
  }

  public enum STATES
  {
    NONE,
    ALIVE,
    DEAD
  }

  public enum ENEMY_TYPE
  {
    NONE,
    MONSTER,
    BOSS
  }

  public enum EXCEPTION_TYPE
  {
    NONE,
    DIZZY,
    FROZEN
  }

  public enum DOT_TYPE
  {
    NONE,
    BURN,
    POISON
  }

  public enum CHARACTER_TYPE
  {
    NONE,
    HERO,
    ENEMY
  }

  public enum HERO_NAME_PART
  {
    NONE = -1,
    PART_0 = 0,
    PART_1 = 1,
    PART_2 = 2,
  }

}

namespace ConstColections.PJEnums.Hero
{
  public enum ATTRIBUTE_TYPE
  {
    NONE,
    STR,
    VIT,
    INT,
    DEX,
    HP,
    HPMax,
    RES,
    ATK,
    MAG,
    DEF,
    AC,
    CRI,
    PEN,
    HIT,
    AVD
  }
}

namespace ConstCollections.PJEnums.Skill
{
  public enum SKILL_STRINGS_LABEL
  {
    NAME,
    BRIEF_FORMAT
  }

  public enum SKILL_TYPE
  {
    NONE,
    INITIATIVE,
    PASSIVE,
    BUFF
  }

  public enum SKILL_TRIGGER_TYPE
  {
    NONE,
    PROBABILITY,
    STATES,
    SKILL_MUST_FAILED,
    DEBUFF,
    IS_ATTACKER,
    IS_DEFENDER
  }

  public enum SKILL_TRIGGER_STATES
  {
    NONE,
    ON,
    OFF
  }

  public enum SKILL_EFFECT_TYPE
  {
    NONE,
    STANDARD_ATTACK_POWER,
    LAST_STAND_ATTACK_POWER,
    CHANGE_ATTRIBUTE,
    CHANGE_DAMAGE,
    CHANGE_HP,
    CHANGE_HIT_COUNT,
    DOT,
    MUST_HIT,
    SKILL_MUST_FAILED,
    TRICK_LEARNING,
    REINFORCE,
    IGNORE_AC,
    IGNORE_DEF,
    SNEER,
    MUST_NOT_BLAST,
    MUST_NOT_HIT,
    CHANGE_AFFECT_RANGE,
    RESURRECTION,
    EXCEPTION
  }

  public enum SKILL_TARGET_TYPE
  {
    NONE,
    SELF_GROUP,
    OTHER_GROUP,
  }

  public enum SKILL_AFFECT_RANGE
  {
    NONE,
    SINGLE_CURRENT,
    ALL_GROUP,
    ALL_GROUP_ALIVE,
    ALL_GROUP_DEAD,
    EXCLUDE_CURRENT,
    EXCLUDE_CURRENT_ALIVE,
    EXCLUDE_CURRENT_DEAD,
    CUSTOM,
  }

  public enum SKILL_CHANGE_TYPE
  {
    NONE,
    POSITIVE,
    NEGATIVE,
  }

  public enum SKILL_AFFECT_TYPE
  {
    NONE,
    CHANGE_HIT_TARGET,
    CHANGE_OTHERS
  }
    
}

namespace ConstCollections.PJEnums.Equipment
{
  public enum EQUIPMENT_TYPE
  {
    NONE,
    WEAPON,
    ARMOR,
    DECORATIONS
  }

  public enum ATTRIBUTE_TYPE
  {
    NONE,
    HP,
    HPMax,
    RES,
    ATK,
    STR,
    MAG,
    VIT,
    DEF,
    INT,
    AC,
    DEX,
    CRI,
    PEN,
    HIT,
    AVD
  }

  public enum EQUIPMENT_COMPARISON_TYPE
  {
    NONE,
    EQUIPMENT_ATTRIBUTE,
    CHARACTER_ATTRIBUTE

  }

  public enum EQUIPMENT_REINFORCE_COST_TYPE
  {
    DIMENSIONCHIP,
    AURA
  }

  public enum EQUIPMENT_REINFORCE_LEVEL
  {
    REINFORCE_SMALL = 0,
    REINFORCE_MIDDLE = 1,
    REINFORCE_BIG = 2,
    REINFORCE_MIRACLE = 3

  }
}

namespace ConstCollections.PJEnums.BattleBottom
{
  public enum BUTTON_POP_STATE
  {
    CAN_NOT_POP,
    CAN_POP

  }
  public enum POP_WINDOW_NEXT_TO
  {
    NONE,
    CLOSE,
    BACK,
    ACHIEVEMENT,
    MAP,
    BATTLE,
    HERO,
    STONE,
    SETTINGS
  }

}
